name: ShellCheck

on:
  push:
    branches:
      - develop
      - main
      - 'releases/**'
    paths:
      - 'lib/**'
      - 'tools/**'
      - 'uac'

  pull_request:
    branches:
      - develop
      - main
      - 'releases/**'
    paths:
      - 'lib/**'
      - 'tools/**'
      - 'uac'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          path: uac

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: artifacts bin config profiles
      