name: Validate Artifacts File

on:
  push:
    branches:
      - develop
      - main
      - 'releases/**'
    paths:
      - 'artifacts/**'

  pull_request:
    branches:
      - develop
      - main
      - 'releases/**'
    paths:
      - 'artifacts/**'

jobs:
  validate-artifacts-file:
    runs-on: ubuntu-latest

    steps:
      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          path: uac

      - name: Get added/modified files
        id: files
        uses: jitterbit/get-changed-files@v1
      
      - name: Validate all added/modified artifacts files
        run: |
          cd uac
          for file in ${{ steps.files.outputs.added_modified }}; do
            if [[ "${file}" == "artifacts/"*.yaml ]]; then
              ./uac --validate-artifacts-file "$file"
            fi
          done
